Repository ethanrossblack/viewing_party_lite_7, pull requests merged in 2023-08, with the labels that each got.

#12 docs: add pr template
  .github/pull_request_template.md
Labels: documentation, core, chore

#13 3 landing page
  .rspec
  Gemfile
  Gemfile.lock
  app/controllers/users_controller.rb
  app/controllers/welcome_controller.rb
  app/models/user.rb
  app/views/layouts/application.html.erb
  app/views/users/new.html.erb
  app/views/users/show.html.erb
  app/views/welcome/index.html.erb
  config/routes.rb
  db/migrate/20230822222452_create_users.rb
  db/schema.rb
  spec/factories/user_factory.rb
  spec/features/welcome_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/support/factory_bot.rb
Labels: core

#14 4 User Registration Page
  app/views/welcome/index.html.erb
  config/routes.rb
  spec/features/users/new_spec.rb
  spec/features/welcome_spec.rb
Labels: enhancement, core

#15 11 user dashboard page
  spec/features/users/show_spec.rb
Labels: core

#17 11 user dashboard page: view
  app/models/user.rb
  app/views/users/_viewing_party.html.erb
  app/views/users/show.html.erb
Labels: core

#16 4 user registration page
  app/controllers/application_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/layouts/application.html.erb
  app/views/users/new.html.erb
  spec/features/users/new_spec.rb
Labels: enhancement

#18 5 dashboard discover movies
  app/controllers/movies_controller.rb
  app/views/movies/discover.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  spec/features/users/show_spec.rb
Labels: enhancement, core

#20 6 7 additions
  .gitignore
  Gemfile
  Gemfile.lock
  bin/rails
  spec/features/movies/discover_spec.rb
  spec/fixtures/vcr_cassettes/top_20_rated_movies.yml
  spec/models/user_spec.rb
  spec/poros/movie_spec.rb
  spec/rails_helper.rb
  spec/services/movies_service_spec.rb
  spec/spec_helper.rb
Labels: enhancement, core, API consumption

#19 6 discover movies page
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/movies_controller.rb
  app/facades/movies_facade.rb
  app/poros/movie.rb
  app/services/movies_service.rb
  app/views/layouts/application.html.erb
  app/views/movies/_keyword_movies.html.erb
  app/views/movies/_top_rated.html.erb
  app/views/movies/discover.html.erb
  app/views/movies/index.html.erb
  bin/rails
  config/routes.rb
  spec/features/movies/discover_spec.rb
  spec/fixtures/vcr_cassettes/top_20_rated_movies.yml
  spec/models/user_spec.rb
  spec/poros/movie_spec.rb
  spec/rails_helper.rb
  spec/services/movies_service_spec.rb
  spec/spec_helper.rb
Labels: enhancement, core, API consumption

#22 8 movie show page ethan
  app/controllers/movies_controller.rb
  app/facades/movies_facade.rb
  app/poros/cast_member.rb
  app/poros/movie.rb
  app/poros/review.rb
  app/services/movies_service.rb
  app/views/movies/show.html.erb
  config/routes.rb
  spec/features/movies/show_spec.rb
  spec/fixtures/vcr_cassettes/Movie_Details_Page/has_a_button_to_create_a_viewing_party.yml
  spec/fixtures/vcr_cassettes/Movie_Details_Page/has_a_button_to_return_to_the_discover_page.yml
  spec/fixtures/vcr_cassettes/Movie_Details_Page/lists_the_first_10_cast_members.yml
  spec/fixtures/vcr_cassettes/Movie_Details_Page/shows_basic_information_about_the_movie.yml
  spec/fixtures/vcr_cassettes/Movie_Details_Page/shows_information_for_every_review.yml
  spec/fixtures/vcr_cassettes/Movie_Details_Page/shows_the_count_of_total_reviews.yml
  spec/poros/cast_member_spec.rb
  spec/poros/movie_spec.rb
Labels: enhancement, help wanted, solo spike

#24 Show, discover page fixes + testing
  app/controllers/viewing_parties_controller.rb
  app/facades/movies_facade.rb
  app/poros/movie.rb
  app/views/movies/_keyword_movies.html.erb
  app/views/movies/_top_rated.html.erb
  app/views/movies/show.html.erb
  app/views/viewing_parties/new.html.erb
  config/routes.rb
  spec/features/movies/discover_spec.rb
  spec/features/movies/show_spec.rb
  spec/fixtures/vcr_cassettes/Movie_Details_Page/has_a_button_to_create_a_viewing_party.yml
  spec/fixtures/vcr_cassettes/Movie_Details_Page/has_a_button_to_return_to_the_discover_page.yml
  spec/fixtures/vcr_cassettes/Movie_Details_Page/lists_the_first_10_cast_members.yml
  spec/fixtures/vcr_cassettes/Movie_Details_Page/shows_basic_information_about_the_movie.yml
  spec/fixtures/vcr_cassettes/Movie_Details_Page/shows_information_for_every_review.yml
  spec/fixtures/vcr_cassettes/Movie_Details_Page/shows_the_count_of_total_reviews.yml
  spec/fixtures/vcr_cassettes/godfather-movie-details.yml
  spec/fixtures/vcr_cassettes/star_wars_keyword_search.yml
  spec/fixtures/vcr_cassettes/top_20_rated_movies.yml
Labels: enhancement, core, API consumption

#26 Test addition and refactor
  app/facades/movies_facade.rb
  app/views/movies/_keyword_movies.html.erb
  app/views/movies/_top_rated.html.erb
  app/views/movies/index.html.erb
  spec/features/movies/show_spec.rb
  spec/features/users/new_spec.rb
  spec/fixtures/vcr_cassettes/Movies_Results/index_page/keyword_search_movies/displays_the_keyword_search_results.yml
  spec/fixtures/vcr_cassettes/Movies_Results/index_page/top_20_rated_movies_search/displays_the_top_20_rated_movies.yml
  spec/fixtures/vcr_cassettes/godfather-movie-details.yml
  spec/fixtures/vcr_cassettes/star_wars_keyword_search.yml
  spec/fixtures/vcr_cassettes/top_20_rated_movies.yml
  spec/poros/movie_spec.rb
  spec/poros/review_spec.rb
Labels: enhancement

#25 New Viewing Party
  app/controllers/movies_controller.rb
  app/controllers/users_controller.rb
  app/controllers/viewing_parties_controller.rb
  app/facades/user_parties_facade.rb
  app/models/user.rb
  app/models/viewing_party.rb
  app/models/viewing_party_user.rb
  app/poros/movie.rb
  app/services/movies_service.rb
  app/views/users/_viewing_party.html.erb
  app/views/users/show.html.erb
  app/views/viewing_parties/new.html.erb
  bin/rails
  config/routes.rb
  db/migrate/20230825164153_create_viewing_parties.rb
  db/migrate/20230825164358_create_viewing_party_users.rb
  db/schema.rb
  spec/factories/viewing_parties.rb
  spec/factories/viewing_party_users.rb
  spec/features/movies/show_spec.rb
  spec/features/viewing_parties/new_spec.rb
  spec/features/welcome_spec.rb
  spec/fixtures/vcr_cassettes/New_Viewing_Party_Page/new_viewing_party_form/displays_the_movie_title_above_a_form.yml
  spec/fixtures/vcr_cassettes/godfather-movie-details.yml
  spec/models/user_spec.rb
  spec/models/viewing_party_spec.rb
  spec/models/viewing_party_user_spec.rb
Labels: enhancement, API consumption, Work In Progress
